# Generated by Django 5.2.8 on 2025-11-18 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('posts', '0002_post_believes_post_doubts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('BELIEVE', 'Believe'), ('DOUBT', 'Doubt')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='interaction',
            unique_together={('user', 'post')},
        ),
    ]
