# Generated by Django 5.2.8 on 2025-11-18 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('deadline', models.DateField()),
                ('image', models.ImageField(upload_to='posts/')),
                ('status', models.CharField(choices=[('wellsee', 'Wellsee'), ('completed', 'Completed')], default='wellsee', max_length=20)),
                ('proof_media', models.ImageField(blank=True, null=True, upload_to='proofs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
